FROM python:3.10-slim-buster
#inside a container
#Make a new folder inside a container
WORKDIR /backend-flask
#inside container outside container
#this contains the libraries you install to run the app
COPY requirements.txt requirements.txt
#Inside container 
# Run python libraries used for the app

RUN pip3 install -r requirements.txt
# outside container .>inside container
# . means everything in current directory
#first period. / backend-flask (outside container
#second period./backend flask (inside container)
COPY . .
#set enviroment variable(env vars)
#inside container and will remain set when the container is run
ENV FLASK_ENV=development

EXPOSE ${PORT}
#cmd(command)
#python3 -m flask run --host=0.0.0.0 --port=4567
CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0", "--port=4567"]